name: Node Continuous Integration

on:
  workflow_dispatch
  #pull_request:
  #  branches: [ master ]
    
defaults:
  run:
    working-directory: Assets/Scripts
env:
  SERVER: ${{ secrets.NPM_REGISTRY_IP }}
  TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
jobs:
  build_and_upload:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cat << EOF > .npmrc
             //$SERVER/:_authToken="$TOKEN"
             EOF
      - run: npm publish --registry http://$SERVER
      - run: echo "DONE"
