name: Node Continuous Integration

on:
  workflow_dispatch
  #pull_request:
  #  branches: [ master ]
    
defaults:
  run:
    working-directory: Assets/Scripts

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: echo "Fertig"
