name: NPM Publish package

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches: [ 'main' ]
    
defaults:
  run:
    working-directory: Assets/Scripts
env:
  SERVER: ${{ secrets.NPM_REGISTRY_IP }}
  TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
jobs:

  publish:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release-please')
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Copy Samples folders
        run: |
            echo "Entering Scripts folder"
            cd Assets/Scripts
            echo "Removing current samples if any"
            rm -rf Samples~
            echo "Creating Samples~ folder"
            mkdir Samples~ && cd $_
            cp ../../Samples/* ./ -r
            echo "Removing meta files"
            find . -type f -name '*.meta' -delete
      - name: ㊙️ Creating NPMRC
        run: |
             cat << EOF > .npmrc
             //$SERVER/:_authToken="$TOKEN"
             EOF
      - name: ⬆️ NPM PUBLISH
        run: npm publish --registry http://$SERVER
      - name: ✅ COMPLETE
        run: echo "DONE"
