name: Release Please

on:
  workflow_dispatch
    
defaults:
  run:
    working-directory: Assets/Scripts

jobs:
  check_and_generate_files:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: com.obert.common
          path: Assets/Scripts
          