name: Unity Tests

on:
  pull_request:
     types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}
        key: Library-CommonPlugin-Standalone
        restore-keys: |
          Library-CommonPlugin-
          Library-
    - uses: game-ci/unity-test-runner@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
          
