name: Unity Tests

on:
  pull_request:
     types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: game-ci/unity-test-runner@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: ${GITHUB_WORKSPACE}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
          
